name: Build Release

on:
  push:
    branches: [main]
  merge_group:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/iron
          check-latest: true
      - uses: MinoruSekine/setup-scoop@v4

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Install gettext
        run: scoop install gettext

      # Not needed since we only build Staging
      #- name: Install WiX Toolset
      #  run: scoop install wixtoolset

      - name: CMake - Build Staging
        working-directory: "${{github.workspace}}"
        run: cmake -DAFX_MULTIBUILD_STAGING=ON -P cmake/MultiBuild.cmake
